In [2]:
#3 Code to explain the basic concepts of Variables, contants and placeholders

In [1]:
import tensorflow as tf

# Disable eager execution to use the session-based model
tf.compat.v1.disable_eager_execution()

# Define a variable
zero = tf.compat.v1.Variable(0, name='zero')

# Define a constant
one = tf.constant(1, name='one')

# Addition operation in tf
new_value = tf.add(zero, one, name='add')

# Update operation
update = zero.assign(new_value)

# Initialize variables
init_op = tf.compat.v1.global_variables_initializer()

# Start a session to run the operations
with tf.compat.v1.Session() as sess:
    # Run the initializer
    sess.run(init_op)
    
    # Run the update operation
    # sess.run(update)
    
    # Print the updated value of the variable
    print(sess.run(zero))  # Output: 1


0


In [2]:
# we need to always run teh session within the 'with' block or else wont work

with tf.compat.v1.Session() as sess:
    # Run the initializer
    sess.run(init_op) #no need every session once in the beinging it enough
    for _ in range(5): 
        sess.run(update)
        print(sess.run(zero))

1
2
3
4
5


In [3]:
hello=tf.constant("hello")
world=tf.constant("world")
helloworld=tf.add(hello,world)

with tf.compat.v1.Session() as sess:
    print(sess.run(helloworld))

b'helloworld'


In [4]:
#placeholder
a=tf.compat.v1.placeholder(tf.float32)
b=a*2

with tf.compat.v1.Session() as sess:
    #feeding a plaeholder with scalar
    # result=sess.run(b, feed_dict={a:3})  #or without giving a varible name, with is better
    result=sess.run(b, {a:3})
    print(result)


6.0


In [5]:
with tf.compat.v1.Session() as sess:
    #feeding a placceholder with vetor of rank1
    result=sess.run(b, feed_dict={a:[3,4,5]})
    print(result)

[ 6.  8. 10.]


In [6]:
dictionary={a:[[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]]} #multidimensional array 3x3x2

with tf.compat.v1.Session() as sess:
    #feeding a placceholder with vetor of rank1
    result=sess.run(b, feed_dict=dictionary)
    print(result)

[[[ 2.  4.  6.]
  [ 8. 10. 12.]
  [14. 16. 18.]]

 [[20. 22. 24.]
  [26. 28. 30.]
  [32. 34. 36.]]]


In [7]:
# how is graph created

In [8]:
graph=tf.compat.v1.get_default_graph()

In [9]:
graph.get_operations()

[<tf.Operation 'zero/Initializer/initial_value' type=Const>,
 <tf.Operation 'zero' type=VarHandleOp>,
 <tf.Operation 'zero/IsInitialized/VarIsInitializedOp' type=VarIsInitializedOp>,
 <tf.Operation 'zero/Assign' type=AssignVariableOp>,
 <tf.Operation 'zero/Read/ReadVariableOp' type=ReadVariableOp>,
 <tf.Operation 'one' type=Const>,
 <tf.Operation 'add/ReadVariableOp' type=ReadVariableOp>,
 <tf.Operation 'add' type=AddV2>,
 <tf.Operation 'AssignVariableOp' type=AssignVariableOp>,
 <tf.Operation 'ReadVariableOp' type=ReadVariableOp>,
 <tf.Operation 'init' type=NoOp>,
 <tf.Operation 'Const' type=Const>,
 <tf.Operation 'Const_1' type=Const>,
 <tf.Operation 'Add_1' type=Add>,
 <tf.Operation 'Placeholder' type=Placeholder>,
 <tf.Operation 'mul/y' type=Const>,
 <tf.Operation 'mul' type=Mul>]

In [10]:
a=tf.constant(10, name="a")

operations=graph.get_operations()
print(operations)

[<tf.Operation 'zero/Initializer/initial_value' type=Const>, <tf.Operation 'zero' type=VarHandleOp>, <tf.Operation 'zero/IsInitialized/VarIsInitializedOp' type=VarIsInitializedOp>, <tf.Operation 'zero/Assign' type=AssignVariableOp>, <tf.Operation 'zero/Read/ReadVariableOp' type=ReadVariableOp>, <tf.Operation 'one' type=Const>, <tf.Operation 'add/ReadVariableOp' type=ReadVariableOp>, <tf.Operation 'add' type=AddV2>, <tf.Operation 'AssignVariableOp' type=AssignVariableOp>, <tf.Operation 'ReadVariableOp' type=ReadVariableOp>, <tf.Operation 'init' type=NoOp>, <tf.Operation 'Const' type=Const>, <tf.Operation 'Const_1' type=Const>, <tf.Operation 'Add_1' type=Add>, <tf.Operation 'Placeholder' type=Placeholder>, <tf.Operation 'mul/y' type=Const>, <tf.Operation 'mul' type=Mul>, <tf.Operation 'a' type=Const>]


In [11]:
for op in graph.get_operations(): print(op.name)

zero/Initializer/initial_value
zero
zero/IsInitialized/VarIsInitializedOp
zero/Assign
zero/Read/ReadVariableOp
one
add/ReadVariableOp
add
AssignVariableOp
ReadVariableOp
init
Const
Const_1
Add_1
Placeholder
mul/y
mul
a
